CREATE TABLE usuarios
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255)                            NOT NULL,
    senha     VARCHAR(255)                            NOT NULL,
    role      VARCHAR(255),
    pessoa_id BIGINT,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE animais
    ADD imagem BYTEA;

ALTER TABLE prontuario
    ADD CONSTRAINT uc_prontuario_animal UNIQUE (animal_id);

ALTER TABLE registro_prontuario
    ADD CONSTRAINT uc_registro_prontuario_agendamento UNIQUE (agendamento_id);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_login UNIQUE (login);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_pessoa UNIQUE (pessoa_id);

ALTER TABLE prontuario
    ADD CONSTRAINT FK_PRONTUARIO_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE usuarios
    ADD CONSTRAINT FK_USUARIOS_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoas (id);

ALTER TABLE diaria_internacao
    ALTER COLUMN peso_no_dia TYPE DECIMAL USING (peso_no_dia::DECIMAL);

ALTER TABLE registro_prontuario
    ALTER COLUMN peso_no_dia TYPE DECIMAL USING (peso_no_dia::DECIMAL);

ALTER TABLE administracoes_medicamentos
    ALTER COLUMN quantidade_administrada TYPE DECIMAL USING (quantidade_administrada::DECIMAL);