CREATE TABLE pessoas
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(100)                            NOT NULL,
    cpf             VARCHAR(15)                             NOT NULL,
    data_nascimento DATE                                    NOT NULL,
    telefone        VARCHAR(20)                             NOT NULL,
    email           VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_pessoas PRIMARY KEY (id)
);

CREATE TABLE clientes
(
    pessoa_id     BIGINT NOT NULL,
    data_cadastro DATE   NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (pessoa_id)
);

CREATE TABLE cargos
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cargo   VARCHAR(255)                            NOT NULL,
    salario DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_cargos PRIMARY KEY (id)
);

CREATE TABLE funcionarios
(
    pessoa_id     BIGINT NOT NULL,
    data_admissao DATE   NOT NULL,
    cargo_id      BIGINT NOT NULL,
    crmv          VARCHAR(255),
    CONSTRAINT pk_funcionarios PRIMARY KEY (pessoa_id)
);

CREATE TABLE animais
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(50)                             NOT NULL,
    especie         VARCHAR(255)                            NOT NULL,
    porte           VARCHAR(255)                            NOT NULL,
    raca            VARCHAR(50)                             NOT NULL,
    sexo            VARCHAR(255)                            NOT NULL,
    cor             VARCHAR(15),
    peso            DOUBLE PRECISION                        NOT NULL,
    castrado        BOOLEAN                                 NOT NULL,
    data_nascimento DATE                                    NOT NULL,
    observacao      VARCHAR(255),
    cliente_id      BIGINT,
    CONSTRAINT pk_animais PRIMARY KEY (id)
);

CREATE TABLE servicos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo           VARCHAR(255)                            NOT NULL,
    veterinario_id BIGINT                                  NOT NULL,
    valor          DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_servicos PRIMARY KEY (id)
);

CREATE TABLE agendamentos
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id             BIGINT                                  NOT NULL,
    servico_id            BIGINT                                  NOT NULL,
    cliente_id            BIGINT                                  NOT NULL,
    data_hora_agendamento TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    observacoes           VARCHAR(255),
    CONSTRAINT pk_agendamentos PRIMARY KEY (id)
);

CREATE TABLE internacao
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id    BIGINT                                  NOT NULL,
    data_entrada TIMESTAMP                               NOT NULL,
    data_saida   TIMESTAMP,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_internacao PRIMARY KEY (id)
);

CREATE TABLE administracoes_medicamentos
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade_administrada DECIMAL(19, 2)                          NOT NULL,
    data_hora               TIMESTAMP                               NOT NULL,
    dosagem                 VARCHAR(255),
    medicamento_id          BIGINT                                  NOT NULL,
    entrada_prontuario_id   BIGINT,
    funcionario_executor_id BIGINT                                  NOT NULL,
    diaria_internacao_id    BIGINT,
    CONSTRAINT pk_administracoes_medicamentos PRIMARY KEY (id)
);

CREATE TABLE medicamento
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produto_id             BIGINT                                  NOT NULL,
    categoria              VARCHAR(255)                            NOT NULL,
    via_administracao      VARCHAR(255),
    dosagem_padrao         VARCHAR(255),
    principio_ativo        VARCHAR(255),
    prescricao_obrigatoria BOOLEAN,
    CONSTRAINT pk_medicamento PRIMARY KEY (id)
);

CREATE TABLE registro_prontuario
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prontuario_id        BIGINT                                  NOT NULL,
    agendamento_id       BIGINT,
    veterinario_id       BIGINT                                  NOT NULL,
    data_hora            TIMESTAMP                               NOT NULL,
    internacao_id        BIGINT,
    peso_no_dia          DECIMAL(19, 2),
    observacoes_clinicas TEXT,
    diagnostico          TEXT,
    CONSTRAINT pk_registro_prontuario PRIMARY KEY (id)
);

CREATE TABLE diaria_internacao
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_hora            TIMESTAMP                               NOT NULL,
    observacoes_clinicas TEXT                                    NOT NULL,
    diagnostico          TEXT                                    NOT NULL,
    peso_no_dia          DECIMAL(19, 2),
    internacao_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_diaria_internacao PRIMARY KEY (id)
);

CREATE TABLE produto
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome               VARCHAR(100)                            NOT NULL,
    descricao          TEXT,
    quantidade_estoque INTEGER                                 NOT NULL,
    CONSTRAINT pk_produto PRIMARY KEY (id)
);

CREATE TABLE prontuario
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id               BIGINT                                  NOT NULL,
    alergias_conhecidas     TEXT,
    condicoes_preexistentes TEXT,
    CONSTRAINT pk_prontuarios PRIMARY KEY (id)
);

ALTER TABLE pessoas
    ADD CONSTRAINT uc_pessoas_cpf UNIQUE (cpf);

ALTER TABLE pessoas
    ADD CONSTRAINT uc_pessoas_email UNIQUE (email);

ALTER TABLE cargos
    ADD CONSTRAINT uc_cargos_cargo UNIQUE (cargo);

ALTER TABLE funcionarios
    ADD CONSTRAINT uc_funcionarios_crmv UNIQUE (crmv);

ALTER TABLE clientes
    ADD CONSTRAINT FK_CLIENTES_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoas (id);

ALTER TABLE funcionarios
    ADD CONSTRAINT FK_FUNCIONARIOS_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoas (id);

ALTER TABLE funcionarios
    ADD CONSTRAINT FK_FUNCIONARIOS_ON_CARGO FOREIGN KEY (cargo_id) REFERENCES cargos (id);

ALTER TABLE animais
    ADD CONSTRAINT FK_ANIMAIS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (pessoa_id);

ALTER TABLE servicos
    ADD CONSTRAINT FK_SERVICOS_ON_VETERINARIO FOREIGN KEY (veterinario_id) REFERENCES funcionarios (pessoa_id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (pessoa_id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_SERVICO FOREIGN KEY (servico_id) REFERENCES servicos (id);

ALTER TABLE administracoes_medicamentos
    ADD CONSTRAINT FK_ADM_MED_ON_MEDICAMENTO FOREIGN KEY (medicamento_id) REFERENCES medicamento (id);

ALTER TABLE administracoes_medicamentos
    ADD CONSTRAINT FK_ADM_MED_ON_REGISTRO_PRONTUARIO FOREIGN KEY (entrada_prontuario_id) REFERENCES registro_prontuario (id);

ALTER TABLE administracoes_medicamentos
    ADD CONSTRAINT FK_ADM_MED_ON_FUNCIONARIO_EXECUTOR FOREIGN KEY (funcionario_executor_id) REFERENCES funcionarios (pessoa_id);

ALTER TABLE administracoes_medicamentos
    ADD CONSTRAINT FK_ADM_MED_ON_DIARIA_INTERNACAO FOREIGN KEY (diaria_internacao_id) REFERENCES diaria_internacao (id);

ALTER TABLE internacao
    ADD CONSTRAINT FK_INTERNACAO_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE medicamento
    ADD CONSTRAINT uc_medicamento_produto_id UNIQUE (produto_id);

ALTER TABLE medicamento
    ADD CONSTRAINT FK_MEDICAMENTO_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produto (id);

ALTER TABLE registro_prontuario
    ADD CONSTRAINT FK_REG_PRONT_ON_PRONTUARIO FOREIGN KEY (prontuario_id) REFERENCES prontuario (id);

ALTER TABLE registro_prontuario
    ADD CONSTRAINT FK_REG_PRONT_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES agendamentos (id);

ALTER TABLE registro_prontuario
    ADD CONSTRAINT FK_REG_PRONT_ON_VETERINARIO FOREIGN KEY (veterinario_id) REFERENCES funcionarios (pessoa_id);

ALTER TABLE registro_prontuario
    ADD CONSTRAINT FK_REG_PRONT_ON_INTERNACAO FOREIGN KEY (internacao_id) REFERENCES internacao (id);

ALTER TABLE diaria_internacao
    ADD CONSTRAINT FK_DIARIA_INT_ON_INTERNACAO FOREIGN KEY (internacao_id) REFERENCES internacao (id);

ALTER TABLE produto
    ADD CONSTRAINT uc_produto_nome UNIQUE (nome);